
url: #Your url here
baseurl: /

permalink: /:slug/

# variables
name: AweSome Personal Weblog Site
description: "Awesome blog collection - 优秀博客收集"
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
